### ISSUE TITLE
Media Path Error

### ISSUE THREAD

**Issue by amrrs** [snow-actions/tweet#172]
Hey Thanks for this action, Somehow the media path doesn't recognize the right file path. 

I've added a file inside the folder shots - /shot/shot.png

```
(node:1676) UnhandledPromiseRejectionWarning: Error: /home/runner/work/hg-spaces-shot/hg-spaces-shot/shots/shot.png not exists
```

I tried a lot of ways but nothing seem to work out, Any tips?

**Comment by SnowCait** [comment]
Do you checkout the repository? (Sorry for forgetting it in README example)

```yml
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - uses: snow-actions/tweet@v1.1.1
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: message
          media_paths: |
            shot/shot.png
      
```
